name: Testing
on: workflow_dispatch
jobs:
  test:
    name: Run unit tests
    runs-on: macos-10.15
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.0,name=iPhone 11 Pro Max']
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.1.0
        with:
          version: '13.0'
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: Example/Pods
          key: ${{ runner.os }}-pods-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-${{ secrets.CACHE_VERSION }}-
      
      - name: Install Dependencies
        run: cd Example && pod install --repo-update       
#        shell: bash
      
      - name: Build and Test
        run: cd Example && fastlane unit_tests
        env: 
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          destination: ${{ matrix.destination }}

      - name: Slather
        run: |
          gem install slather
          slather
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./cobertura.xml
          flags: unittests
          verbose: true
